services:
  api-gateway:
    image: your-api-gateway-image
    ports:
      - "8080:8080"  # Altere a porta externa se necessário

  auth-service:
    image: markfest-auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Altere a porta externa se necessário
    environment:
      - JWT_SECRET=${JWT_SECRET:-""}

  payment-service:
    image: markfest-payment-service:latest
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"  # Altere a porta externa se necessário
    environment:
      - JWT_SECRET=${JWT_SECRET:-""}

  chat-service:
    image: your-chat-service-image
    ports:
      - "8083:8080"  # Altere a porta externa se necessário

  event-service:
    image: markfest-event-service:latest
    build:
      context: ./event-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"  # Altere a porta externa se necessário
    environment:
      - JWT_SECRET=${JWT_SECRET:-""}

  notification-service:
    image: markfest-notification-service:latest
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"  # Altere a porta externa se necessário
    environment:
      - JWT_SECRET=${JWT_SECRET:-""}

  participation-service:
    image: markfest-participation-service:latest
    build:
      context: ./participation-service
      dockerfile: Dockerfile
    ports:
      - "8086:8080"  # Altere a porta externa se necessário
    environment:
      - JWT_SECRET=${JWT_SECRET:-""}

  service-discovery:
    image: your-service-discovery-image
    ports:
      - "8761:8761"  # Altere a porta externa se necessário
