version: '3.8'

services:
  api-gateway:
    image: your-api-gateway-image
    ports:
      - "8080:8080"  # Altere a porta externa se necessário

  auth-service:
    image: auth-service-image  # Use o nome correto da sua imagem
    ports:
      - "8081:8080"  # Altere a porta externa se necessário

  payment-service:
    image: your-payment-service-image
    ports:
      - "8082:8080"  # Altere a porta externa se necessário

  chat-service:
    image: your-chat-service-image
    ports:
      - "8083:8080"  # Altere a porta externa se necessário

  event-service:
    image: your-event-service-image
    ports:
      - "8084:8080"  # Altere a porta externa se necessário

  notification-service:
    image: your-notification-service-image
    ports:
      - "8085:8080"  # Altere a porta externa se necessário

  participation-service:
    image: your-participation-service-image
    ports:
      - "8086:8080"  # Altere a porta externa se necessário

  service-discovery:
    image: your-service-discovery-image
    ports:
      - "8761:8761"  # Altere a porta externa se necessário
